### ISSUE TITLE
Update to Laravel 6.x

### ISSUE THREAD

**Issue by philipboeken** [bitsnbolts/laravel-collection-macros#1]
Hi Thijs, love your work! My application heavily relies on your wonderful package, and I'd love to update my Laravel-based app to version 6.x, but I'm having a problem with this most awesome package. Currently you require Illuminate/Support 5.8.*, but I'd like it to require ^6.0 of iig hoger dan 6, so I can continue using it. 

Thanks!

**Comment by thijsvdanker** [comment]
@philipboeken thanks ☺️

I've just tagged the 2.0.0 release with Laravel 6.x support: https://github.com/bitsnbolts/laravel-collection-macros/releases/tag/2.0.0

So if you update your composer.json to
```
        "bitsnbolts/laravel-collection-macros": "^2.0",
```

you should be all sorted.
